### ISSUE TITLE
Make "disabled" props working

### ISSUE THREAD

**Issue by RiusmaX** [Dealana/React-Native-Selection#1]
I need to disable the selector, can you add a "disabled" property ? 

Thanks in advance :)

**Comment by thinnakrit** [comment]
Thank you for issue!

I edit and update code complete you can update by 

> npm install react-native-selection

, and you can edit below if don't to update

1. Open file name index.js below
` './node_modules/react-native-selection/index.js' `

or see the example 

> https://github.com/Dealana/React-Native-Selection/blob/master/index.js

2. See line 138 - 145 delete code and add 
```
if(data.disable)
return(
<View style={styles.disable}>
{icon}
<Text>{data.name}</Text>
</View>
)
else
return(
<TouchableOpacity key={k} onPress={()=> this.onSelected(data.name, data.value)}>
<View style={styles.option}>
 {icon}
<Text>{data.name}</Text>
</View>
</TouchableOpacity>
)
```

3. Add props name 'disable: true'  if want to disable list on your select list
